### PR TITLE
Make add-on build process really working

### PR DESCRIPTION
**Pull request by lukaszgo1**
Do not provide full path to the output in .t2t file as it makes build fail
@SugarCaneNS Have you tested this at all before committing?

### CODE REVIEW

**Comment by JulienCochuyt** [comment]
@lukaszgo1, regarding txt2tags:
IINW, it also works without setting PYTHONPATH manually if txt2tags is installed (pip install txt2tags) - but as it is meant to be dropped pretty soon in favor of Markdown, I guess your solution goes the right way.
Have you checked it against a Python 3 build?
Python 3 banned implicit relative imports, so locating `txt2tags.py` in `site_scons` would only work if `site_scons` is in turn in the PYTHONPATH - which I did not check.

**Comment by lukaszgo1** [comment]
I do not think version of TXT2tags included inn the repo is Python 3 compatible at all.

**Comment by JulienCochuyt** [comment]
@lukaszgo1 wrote:
> I do not think version of TXT2tags included inn the repo is Python 3 compatible at all.

Good point.

**Comment by SugarCaneNS** [comment]
The version of txt2tags contained in the repo is very old, probably from about 2012.  So it will not be py3-compatible.  As I have stated in other places, the NVDA portion of this project is all over the place because prior to the last few weeks, the code and docs had not been substantially touched since about 2014.  Currently, when one attempts to run the plugin in the scratchpad, there are problems where there is a timeout when the plugin waits for the system caret to move.  It needs a fair bit of work to get it up and running again.  But I had decided not to make any contributions until @lukaszgo1 had finished his work integrating Derek Riemer's changes.

**Comment by SugarCaneNS** [comment]
Also, since we are thinking of transitioning to Markdown, I did not (and do not) think there is much point in updating txt2tags.  Perhaps for testability but otherwise this was not an option I had considered.

**Pull request merged**
