### PR TITLE
Integrate dereks changes

### LINKED ISSUE #5: Incorporate Derek Riemer's External Changes to the Latex-Access NVDA Plugin
Some time ago, @DerekRiemer created his own repository on Github, many of which would be beneficial to this project.  The most notable changes would be:

- Changes to global key bindings, which helps in avoiding clashes with other applications;
- More reliable support for the matrix browser with multiple matrices; and 
- Direct import of the latex-access package, rather  then relying solely on the registered COM objects, which allows for more coding flexability.
-
Unfortunately, adding these changes would probably require a certain amount of manual work.  Merging would not be fiable for adding these features, as Derek's repo does not reflect our current changes.

### LINKED ISSUE #6: Globally Index Latex-Access in PIP; integrate into lib/site-packages
I am just thinking out loud here.  But if, as Lukasz has suggested, we want to use Derek Riemer's changes, would it make it easier for ourselves if we package latex-access as part of the library, indexing it on the Python Package Index? I realise that Derek has ported the package over to his own repo and imports it accordingly.  But I think this will get too hard to manage.  Derek's repo seems to be somewhat NVDA-centric, so we may end up losing JAWS / Emacs functionality if we use the code in the way that Derek has done.  Does anyone have any thoughts / suggestions in this regard?

### PR DESCRIPTION
**Pull request by lukaszgo1**
This is still a draft. I will change type of the PR when it would be ready for review.
Closes #5  Closes #6 
## This PR would contain the following:
- [ ] LaTeX access would be imported as a package rather than via COM server.
- [ ] Support for multiple matrices from Derek's plugin.
- [ ] A keys used for the plugin would be less likely to clash with these provided by the application.
(Note to self: Convert scripts from matrixbrowser to use scriptDecorator.)
- [ ] I'll  try to make LaTeX access editable 
class present in the MR only when translation is active.
- [ ] I'll  also try to use NVDA build in script to announce current line when translation is off.
- [ ] Copying LA files should happen automatically as part of SCons.
- [ ] The documentation needs to be rewritten and converted to Markdown. At the moment add-on build process fails unless folder containing txt2tags is manually added to PYTHONPATH, so it makes sense to switch to Markdown completely.
- [ ] I'll also clean *.txt files from NVDA folder - now that we have proper bug tracker it makes sense to move bugs and todo list to a separate issues.

I am not going to take the following functions from Derek's code:
- Braille region - It is too buggy at the moment - I will go back to the flash messages, but reworking braille support should be something to keep in mint.
- Function that changes voice parameters depending on what math is read - it is not taking into account different translations and in my view this should be configurable.

My goal is to be compatible with 2019.2.1 and 2019.3, but if being compatible with both would prove to be difficult I'd stick with 2019.3

### CODE REVIEW

**Comment by SugarCaneNS** [comment]
@lukaszgo1, shall I leave it up to you to git rm bugs and todo?

**Comment by lukaszgo1** [comment]
If you can. I'll do this at the end, when all points from them are either addressed, or moved to the separate issues.

**Comment by SugarCaneNS** [comment]
@lukaszgo1, who do you think should re-format / convert the NVDA addon readme from txt2tags to markdown? Should I do this, or do you want to do this?

**Comment by JulienCochuyt** [comment]
@SugarCaneNS wrote:
> @lukaszgo1, who do you think should re-format / convert the NVDA addon readme from txt2tags to markdown? Should I do this, or do you want to do this?

The current build process should handle just fine `readme.t2t` being simply replaced by `readme.md` to generate the HTML documentation.
However, once you converted to Markdown, you might as well wish to revert commit 8a5440fa25c as txt2tags integration will no longer be needed.

**Comment by lukaszgo1** [comment]
@SugarCaneNS I'll convert to markdown at the end. Doing it now makes no sense, as the documentation would need to be substantially rewritten.

**Comment by SugarCaneNS** [comment]
@JulienCochuyt, I think what @lukaszgo1 is trying to say is that the conversion process is not as simple as renaming the readme doc from .t2t to .md.  There are significant syntactical changes between the two document preparation systems.

**Comment by JulienCochuyt** [comment]
@SugarCaneNS wrote:
> @JulienCochuyt, I think what @lukaszgo1 is trying to say is that the conversion process is not as simple as renaming the readme doc from .t2t to .md. There are significant syntactical changes between the two document preparation systems.

Sure there are.
I was just pointing out that this can be achieved without changes to the current `sconstruct` file, which might nevertheless benefit from the mentioned clean-up afterwards.

**Comment by lukaszgo1** [comment]
I am closing this one for now. My branch got super messy due to differences in case for addon directory.

**Pull request closed without merging**
