### PR TITLE
Original / Nathaniel

### PR DESCRIPTION
**Pull request by SugarCaneNS**
This branch merge will contain updates to documentation and source code, reflecting the migration from SourceForge to Github.  Also contains a minor update to contributors.txt.  In addition, the centralised documentation now contains less information, instructing the end-user to consult the relevant documentation for JAWS, NVDA, or Emacs.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
You have converted all files to Windows line endings which creates a huge dif. I believe this was done by mistake, right?

**Comment by SugarCaneNS** [comment]
Oh, thanks for pointing that out.  There will still be a huge diff I think because I modified just about every Python source file to include references to the Github repo.  But I have also been both checking-out and committing as-is.  I have modified my Git for Windows installation accordingly.  I should now be checking out as-is but committing unix-style (\n) line endings.  @JulienCochuyt, what should I do next?

**Comment by lukaszgo1** [comment]
While it would improve situation for the future commits, for this one files are still converted to CR LF.  It might make sense to either revert it and reapply changes, or convert affected files back to LF.

**Comment by JulienCochuyt** [comment]
@SugarCaneNS, most NVDA related projects are configured "core.autocrlf=true", that is check-out Windows-style, check-in Unix-style - which is btw the default setting on Windows installations.
I agree with @lukaszgo1 this needs to be fixed before merging.

**Comment by SugarCaneNS** [comment]
@JulienCochuyt, @lukaszgo1: I have done as you both suggested but with the only exception of the files in the JAWS directory.  I can change those too if you like but JAWS tends not to recognise \n-only line endings.  If I merge these changes now, I am concerned that there will be duplicate messages in the commit log and changes within the index.  As I have already made the appropriate manual conflict resolutions that would have been necessary between Julien's and my changes, can I just commit them anyway? I am afraid that to reset / revert now would be extremely tedious.

**Comment by SugarCaneNS** [comment]
Also, I hope this is okay but in case anyone is wondering why, perhaps I should point out that I have deliberately removed nvda/.gitignore, placing its contents (along with the appropriate additional references to the sub-directory) in the main latex-access directory.  For this project at least, considering that it is more than just an NVDA plugin, I think it would be easier to manage if all of the relevant contents were placed into one file.

**Comment by SugarCaneNS** [comment]
I have added my changes to the documentation, contained in original/nathaniel, to original/master.  I am hoping, however, that there will be no future conflicts with Lukasz's proposed changes, since I observe from committed changes that there is already a merge of Julien's changes, which I have also merged into my changes.  Perhaps it will only create duplicates in the commit log.  But this may mean, in other words, that @JulienCochuyt's changes have been merged and will be ultimately re-merged at least three times.

**Comment by JulienCochuyt** [comment]
@SugarCaneNS wrote:
> But this may mean, in other words, that @JulienCochuyt's changes have been merged and will be ultimately re-merged at least three times.

There is no problem at all with this. Git blame will still point out the first commit introducing the change.
What is more problematic, though, is that it seems you merged your changes without first taking care of the line ending issues pointed out in https://github.com/SugarCaneNS/latex-access/pull/4#issuecomment-553377705

**Comment by SugarCaneNS** [comment]
@JulienCochuyt, The line ending issue should already be fixed within most files, the only notable exception being the files within the JAWS directory.

**Pull request merged**
